### ISSUE TITLE
Build failures with mtl-2.3

### ISSUE THREAD

**Issue by sjakobi** [xc-jp/aeson-commit#15]
When I build this package with the `mtl-2.3` release I get this failure:

```
src/Data/Aeson/Commit.hs:64:40: error:
    Not in scope: type constructor or class ‘ExceptT’
   |
64 | newtype Commit a = Commit {unCommit :: ExceptT [Parser Void] Parser a}
   |                                        ^^^^^^^
```

This build failure is due to https://github.com/haskell/mtl/issues/117 which will be fixed in a follow-up release of `mtl`.

Building with a version of `mtl` that includes a fix to that issue, I'm getting

```
src/Data/Aeson/Commit.hs:73:3: error:
    Variable not in scope:
      lift :: Parser b -> ExceptT [Parser Void] Parser b
   |
73 |   lift $ post a
   |   ^^^^
```

**Comment by jonascarpay** [comment]
Thanks for reporting, it should be fixed.
