### ISSUE TITLE
Error messages show incorrect JSONPath

### ISSUE THREAD

**Issue by considerate** [xc-jp/aeson-commit#2]
The aeson library has the concept of a JSONPath that is shown on parse errors like
```
Error in $.posts[0].comments[2]: <error text>
```

These JSONPaths are discarded when parsing using `Commit`, so while the backtracking is limited to output the error message at the relevant point, the error messages are still quite uninformative if the source JSON is large.

**Comment by cdepillabout** [comment]
See also the message in https://github.com/xc-jp/aeson-commit/pull/1#issuecomment-586942201

**Comment by considerate** [comment]
Fixed in #3
